export const data = [
  // -------------------------- Super Stockist---------------------
  {
    type: "Super Stockist",
    state: "Bihar",
    area: "Hajipur",
    business: "Work Force",
    name: "Mr. Avinash Prashant",
    mobile: "7870748399",
    email: "vnshpthk@gmail.com",
    zone: "Zone 2",
    address:
      "Alakh Niwas, Basant Bihar colony, Dighi kala west, Vaishali, Bihar, 844102",
  },
  {
    type: "Super Stockist",
    state: "Bihar",
    area: "Gaya",
    business: "Shree Balaji Traders",
    name: "Mr. Rajeev Ranjan",
    mobile: "9934629530",
    email: "rajivpk89@gmail.com",
    zone: "Zone 1",
    address: "Bara Guraru, Po+Ps- Guraru, Distt- Gaya, Pin code-824118",
  },
  {
    type: "Super Stockist",
    state: "Bihar",
    area: "Patna",
    business: "Sushil Enterprises",
    name: "Mr. Sushil Kumar",
    mobile: "6200262714",
    email: "sushil.kunkun@gmail.com",
    zone: "Zone 1",
    address:
      "Vishwarkarma Market, Opp-Eden Apartment, Urja Nagar, Danapur, Khrgaul Road, Patna- 801503",
  },
  {
    type: "Super Stockist",
    state: "Telangana",
    area: "Hyderabad",
    business: "Limra Traders",
    name: "Mir. Mouzam Ali",
    mobile: "9014859893",
    email: "mirmouzam@gmail.com",
    zone: "South",
    address:
      "17-2-1198/8, Jawawhar pura, Yakutpura, Behind Apple Hospital, Charminar,  Hyderabad, Telangana, 500023",
  },

  {
    type: "Super Stockist",
    state: "Uttar Pradesh",
    area: "Mutthi Ganj (Prayagraj)",
    business: "M/s Gyanvi Enterprises ",
    name: "Mr. Vikash Kumar Gupta",
    mobile: "6387797616",
    email: "vksgupta947@gmail.com",
    zone: "Prayagraj Division",
    address: "91A/75C/2H, Malviya Nagar, MutthiGanj, Prayagraj, 211003",
  },

  // -------------------------- Distributor -------------------------

  {
    type: "Distributor",
    state: "Bihar",
    area: "Hajipur",
    business: "Jeet Telecom",
    name: "Mr. Kamal Jeet Choudhary ",
    mobile: "9905640570",
    email: "kamaljeetchoudhary93962@gmail.com",
    zone: "Zone 2",
    address: "Bagmail Hajipur Vaishali, 844101",
  },

  {
    type: "Distributor",
    state: "Bihar",
    area: "Gopalganj",
    business: "Sonali Enterprises",
    name: "Mr. Prabhakar Tiwari",
    mobile: "9523038408",
    email: "prabhakart774@gmail.com",
    zone: "Zone 2",
    address: "Bhore, Chaarmuhani near Chahat, 841426",
  },

  {
    type: "Distributor",
    state: "Bihar",
    area: "Patna",
    business: "Kailash Enterprises",
    name: "Mr. Sharwan Kumar",
    mobile: "8581883417",
    email: "sharwan9100@gmail.com",
    zone: "Zone 1",
    address: "Adarsh Colony, Near- Child hospital, 800001, Patna, Bihar",
  },

  {
    type: "Distributor",
    state: "Bihar",
    area: "Dighi kala (Vaishali)",
    business: "Maa Kaushlya Traders",
    name: "Mr. Mithu Kumar",
    mobile: "9262543561",
    email: "kr.mithuyadav020@gmail.com",
    zone: "Zone 2",
    address: "Dighi kala west Hajipur, Near 54/AC Gate, Yaduwansi Nagar",
  },

  {
    type: "Distributor",
    state: "Bihar",
    area: "Mahnar (Vaishali)",
    business: "Shiv shakti Enterprises",
    name: "Mr. Santosh Kumar Singh",
    mobile: "7209438100",
    email: "sshakitenterprises97@gmail.com",
    zone: "Zone 2",
    address: "Station Road, Mahnar, Vaishali, Bihar Near Chuda Mill, 844506",
  },
  {
    type: "Distributor",
    state: "Bihar",
    area: "Mahua (Vaishali)",
    business: "Vaishnavi Enterprises",
    name: "Mr. Lalan Kumar",
    mobile: "9491553215",
    email: "lkumar94915@gmail.com",
    zone: "Zone 2",
    address: "Ward no-6, Chhatwara(Mahua), 844122",
  },
  {
    type: "Distributor",
    state: "Bihar",
    area: "West Champaran",
    business: "Pallavi Traders",
    name: "Ms. Pallavi Kumari",
    mobile: "9939898370",
    email: "arjunajanabibth@gmail.com",
    zone: "Zone 2",
    address:
      "M/S PALLAVI TRADERS, Vill - Amwa Majhar, Tola- Chauraha, Majhaulia, Pashchim Champaran, Bihar, 845459",
  },

  {
    type: "Distributor",
    state: "Bihar",
    area: "Purnia",
    business: "Baby Bharti Traders",
    name: "Mrs. Baby Bharti",
    mobile: "9006712936",
    email: "babybhartiglobal@gmail.com",
    zone: "Zone 3",
    address:
      "MP 120, Ward no-14, AT W/O Nawal kishor Mandal, Indira nagar, Housing Colony Purnia, 854301",
  },

  {
    type: "Distributor",
    state: "Bihar",
    area: "Patna-Bihta ",
    business: "Satendra Kirana & General Store",
    name: "Mr. Amit Raj",
    mobile: "9708989663",
    email: "amitraj.ar486@gmail.com",
    zone: "Zone 1",
    address: "Moriyama, Datiyana, Bikram, Patna, 801104, Bihar",
  },

  {
    type: "Distributor",
    state: "Telangana",
    area: "Hyderabad",
    business: "Galaxy Enterprises",
    name: "Mir. Mubashir Ali",
    mobile: "9542517864",
    email: "mirmubashirali@333@gmail.com",
    zone: "South",
    address: "17-3-199/36, Dabeerpura, Nagabowli, Telangana, Hyderabad 500023",
  },

  {
    type: "Distributor",
    state: "Telangana",
    area: "Hyderabad",
    business: "QR Enterprises",
    name: "Md. Khisar Ali",
    mobile: "8712251970",
    email: "baba03657@gmail.com",
    zone: "South",
    address: "19-3-262/A/13/16, mustafa nagar, Jahanuma, Hyderabad, 500053",
  },

  {
    type: "Distributor",
    state: "Telangana",
    area: "Hyderabad",
    business: "SS Traders",
    name: "Mr. Abdus salam ",
    mobile: "9396632261",
    email: "abdussalamsaleem783@gmail.com",
    zone: "South",
    address:
      "9-4-62/85, Near Diamond Jublee School, Nizam Colony, Tolichowki, Hyderabad, 500008",
  },

  {
    type: "Distributor",
    state: "Uttar Pradesh",
    area: "Sadar Tehsil (Prayagraj)",
    business: "S.K.Traders",
    name: "Mr.Suresh Kumar Yadav",
    mobile: "9839824335",
    email: "skumaryadav088@gmail.com",
    zone: "Prayagraj Division",
    address: "902/667, Krishna Nagar, Kidganj, Prayagraj, Pin Code-211003",
  },

  //   {
  //     type: " ",
  //     state: " ",
  //     area: " ",
  //     business: " ",
  //     name: " ",
  //     mobile: " ",
  //     email: " ",
  //     zone: " ",
  //     address: " ",
  //   },
];
