const data = [
  {
    model: "RM-3S10",
    cooling_capacity: "3400 W",
    power: "980 W",
    iseer: "3.91",
    star: "3 STAR",
    voltage: "230V/AC/50Hz",
    speed: "Yes",
    fin_color: "Blue",
    tube_diameter: "No",
    idu_air_flow_turbo: "Yes",
    odu_fan_speed: "Variable Speed",
    condenser_row: "No",
    condenser_tube_dia: "No",
    condenser_fin_color: "Blue",
    idu_noise_level: "No",
    odu_noise_level: "No",
    refrigerant_type: "R-32",
    pm_filter: "Yes",
    temperature_display: "Yes",
    self_diagnosis: "Yes",
    auto_restart: "Yes",
    hydrophilic_fins: "No",
    sleep_mode: "Yes",
    remote_blacklight: "Yes",
    auto_protection: "Yes",
    timer: "Yes",
    dry_mode: "Yes",
    turbo_mode: "Yes",
    energy_saver: "Yes",
    anti_viral_filter: "Yes",
    swing_4_way: "No",
    convertiable_4_way: "Yes",
    anti_rust_coating: "Yes",
    inverter: "Yes",
  },
  {
    model: "RM-5S10",
    cooling_capacity: "3500 W",
    power: "930 W",
    iseer: "4.9",
    star: "5 STAR",
    voltage: "230V/AC/50Hz",
    speed: "Yes",
    fin_color: "Blue",
    tube_diameter: "No",
    idu_air_flow_turbo: "Yes",
    odu_fan_speed: "Variable Speed",
    condenser_row: "No",
    condenser_tube_dia: "No",
    condenser_fin_color: "Blue",
    idu_noise_level: "No",
    odu_noise_level: "No",
    refrigerant_type: "R-32",
    pm_filter: "Yes",
    temperature_display: "Yes",
    self_diagnosis: "Yes",
    auto_restart: "Yes",
    hydrophilic_fins: "No",
    sleep_mode: "Yes",
    remote_blacklight: "Yes",
    auto_protection: "Yes",
    timer: "Yes",
    dry_mode: "Yes",
    turbo_mode: "Yes",
    energy_saver: "Yes",
    anti_viral_filter: "Yes",
    swing_4_way: "No",
    convertiable_4_way: "Yes",
    anti_rust_coating: "Yes",
    inverter: "Yes",
  },
  {
    model: "RM-3S15",
    cooling_capacity: "5180 W",
    power: "1680 W",
    iseer: "3.91",
    star: "3 STAR",
    voltage: "230V/AC/50Hz",
    speed: "Yes",
    fin_color: "Blue",
    tube_diameter: "No",
    idu_air_flow_turbo: "Yes",
    odu_fan_speed: "Variable Speed",
    condenser_row: "No",
    condenser_tube_dia: "No",
    condenser_fin_color: "Blue",
    idu_noise_level: "No",
    odu_noise_level: "No",
    refrigerant_type: "R-32",
    pm_filter: "Yes",
    temperature_display: "Yes",
    self_diagnosis: "Yes",
    auto_restart: "Yes",
    hydrophilic_fins: "No",
    sleep_mode: "Yes",
    remote_blacklight: "Yes",
    auto_protection: "Yes",
    timer: "Yes",
    dry_mode: "Yes",
    turbo_mode: "Yes",
    energy_saver: "Yes",
    anti_viral_filter: "Yes",
    swing_4_way: "No",
    convertiable_4_way: "Yes",
    anti_rust_coating: "Yes",
    inverter: "Yes",
  },
  {
    model: "RM-5S15",
    cooling_capacity: "5180 W",
    power: "1600 W",
    iseer: "4.9",
    star: "5 STAR",
    voltage: "230V/AC/50Hz",
    speed: "Yes",
    fin_color: "Blue",
    tube_diameter: "No",
    idu_air_flow_turbo: "Yes",
    odu_fan_speed: "Variable Speed",
    condenser_row: "No",
    condenser_tube_dia: "No",
    condenser_fin_color: "Blue",
    idu_noise_level: "No",
    odu_noise_level: "No",
    refrigerant_type: "R-32",
    pm_filter: "Yes",
    temperature_display: "Yes",
    self_diagnosis: "Yes",
    auto_restart: "Yes",
    hydrophilic_fins: "No",
    sleep_mode: "Yes",
    remote_blacklight: "Yes",
    auto_protection: "Yes",
    timer: "Yes",
    dry_mode: "Yes",
    turbo_mode: "Yes",
    energy_saver: "Yes",
    anti_viral_filter: "Yes",
    swing_4_way: "No",
    convertiable_4_way: "Yes",
    anti_rust_coating: "Yes",
    inverter: "Yes",
  },
  {
    model: "RM-3S20",
    cooling_capacity: "6000 W",
    power: "2110 W",
    iseer: "3.91",
    star: "3 STAR",
    voltage: "230V/AC/50Hz",
    speed: "Yes",
    fin_color: "Blue",
    tube_diameter: "No",
    idu_air_flow_turbo: "Yes",
    odu_fan_speed: "Variable Speed",
    condenser_row: "No",
    condenser_tube_dia: "No",
    condenser_fin_color: "Blue",
    idu_noise_level: "No",
    odu_noise_level: "No",
    refrigerant_type: "R-32",
    pm_filter: "Yes",
    temperature_display: "Yes",
    self_diagnosis: "Yes",
    auto_restart: "Yes",
    hydrophilic_fins: "No",
    sleep_mode: "Yes",
    remote_blacklight: "Yes",
    auto_protection: "Yes",
    timer: "Yes",
    dry_mode: "Yes",
    turbo_mode: "Yes",
    energy_saver: "Yes",
    anti_viral_filter: "Yes",
    swing_4_way: "No",
    convertiable_4_way: "Yes",
    anti_rust_coating: "Yes",
    inverter: "Yes",
  },
  {
    model: "RM-5S20",
    cooling_capacity: "6300 W",
    power: "2100 W",
    iseer: "4.9",
    star: "5 STAR",
    voltage: "230V/AC/50Hz",
    speed: "Yes",
    fin_color: "Blue",
    tube_diameter: "No",
    idu_air_flow_turbo: "Yes",
    odu_fan_speed: "Variable Speed",
    condenser_row: "No",
    condenser_tube_dia: "No",
    condenser_fin_color: "Blue",
    idu_noise_level: "No",
    odu_noise_level: "No",
    refrigerant_type: "R-32",
    pm_filter: "Yes",
    temperature_display: "Yes",
    self_diagnosis: "Yes",
    auto_restart: "Yes",
    hydrophilic_fins: "No",
    sleep_mode: "Yes",
    remote_blacklight: "Yes",
    auto_protection: "Yes",
    timer: "Yes",
    dry_mode: "Yes",
    turbo_mode: "Yes",
    energy_saver: "Yes",
    anti_viral_filter: "Yes",
    swing_4_way: "No",
    convertiable_4_way: "Yes",
    anti_rust_coating: "Yes",
    inverter: "Yes",
  },
];

export default data;
