export default {
  states: [
    {
      stateValue: "Bihar",
      stateName: "Bihar",
    },
    {
      stateValue: "UP",
      stateName: "Uttar Pradesh (UP)",
    },
    {
      stateValue: "Gujarat",
      stateName: "Gujarat",
    },
    {
      stateValue: "Telangana",
      stateName: "Telangana",
    },
  ],
  STOCKIST: {
    Gujarat: [{}],
    Telangana: [{}],
    UP: [
      {
        locationValue: "Aligarh",
        locationName: "Aligarh Division",
      },
      {
        locationValue: "Agra",
        locationName: "Agra Division",
      },
      {
        locationValue: "Azamgarh",
        locationName: "Azamgarh Division",
      },
      {
        locationValue: "Prayagraj",
        locationName: "Prayagraj Division",
      },
      {
        locationValue: "Bareilly",
        locationName: "Bareilly Division",
      },
      {
        locationValue: "Basti",
        locationName: "Basti Division",
      },
      {
        locationValue: "Gonda",
        locationName: "Gonda Division",
      },
      {
        locationValue: "Ayodhya",
        locationName: "Ayodhya Division",
      },
      {
        locationValue: "Banda",
        locationName: "Banda Division",
      },
      {
        locationValue: "Gorakhpur",
        locationName: "Gorakhpur Division",
      },
      {
        locationValue: "Kanpur",
        locationName: "Kanpur Division",
      },
      {
        locationValue: "Jhansi",
        locationName: "Jhansi Division",
      },
      {
        locationValue: "Lucknow",
        locationName: "Lucknow Division",
      },
      {
        locationValue: "Mirzapur",
        locationName: "Mirzapur Division",
      },
      {
        locationValue: "Meerut",
        locationName: "Meerut Division",
      },
      {
        locationValue: "Moradabad",
        locationName: "Moradabad Division",
      },
      {
        locationValue: "Varanasi",
        locationName: "Varanasi Division",
      },
      {
        locationValue: "Saharanpur",
        locationName: "Saharanpur Division",
      },
    ],
    Bihar: [
      {
        locationValue: "Patna",
        locationName: "Patna (District)",
      },
      {
        locationValue: "Gaya",
        locationName: "Gaya (District)",
      },
      {
        locationValue: "Nawada",
        locationName: "Nawada (District)",
      },
      {
        locationValue: "Jamui",
        locationName: "Jamui (District)",
      },
      {
        locationValue: "Bhagalpur",
        locationName: "Bhagalpur (District)",
      },
      {
        locationValue: "Purnia",
        locationName: "Purnia (District)",
      },
      {
        locationValue: "Vaishali",
        locationName: "Vaishali (District)",
      },
      {
        locationValue: "East Champaran",
        locationName: "East Champaran (District)",
      },
      {
        locationValue: "Madhepura",
        locationName: "Madhepura (District)",
      },
      {
        locationValue: "Siwan",
        locationName: "Siwan (District)",
      },
    ],
  },
  DISTRIBUTOR: {
    Gujarat: [{}],
    Telangana: [{}],
    UP: [
      {
        locationValue: "Aligarh",
        locationName: "Aligarh (District)",
      },
      {
        locationValue: "Etah",
        locationName: "Etah (District)",
      },
      {
        locationValue: "Hathras",
        locationName: "Hathras (District)",
      },
      {
        locationValue: "Kasganj",
        locationName: "Kasganj (District)",
      },
      {
        locationValue: "Agra",
        locationName: "Agra (District)",
      },
      {
        locationValue: "Mathura",
        locationName: "Mathura (District)",
      },
      {
        locationValue: "Mainpuri",
        locationName: "Mainpuri (District)",
      },
      {
        locationValue: "Firozabad",
        locationName: "Firozabad (District)",
      },
      {
        locationValue: "Azamgarh",
        locationName: "Azamgarh (District)",
      },
      {
        locationValue: "Ballia",
        locationName: "Ballia (District)",
      },
      {
        locationValue: "Mau",
        locationName: "Mau (District)",
      },
      {
        locationValue: "Prayagraj",
        locationName: "Prayagraj (District)",
      },
      {
        locationValue: "Fatehpur",
        locationName: "Fatehpur (District)",
      },
      {
        locationValue: "Kaushambi",
        locationName: "Kaushambi (District)",
      },
      {
        locationValue: "Pratapgarh",
        locationName: "Pratapgarh (District)",
      },
      {
        locationValue: "Bareilly",
        locationName: "Bareilly (District)",
      },
      {
        locationValue: "Pilibhit",
        locationName: "Pilibhit (District)",
      },
      {
        locationValue: "Shahjahanpur",
        locationName: "Shahjahanpur (District)",
      },
      {
        locationValue: "Badaun",
        locationName: "Badaun (District)",
      },
      {
        locationValue: "Basti",
        locationName: "Basti (District)",
      },
      {
        locationValue: "Sant Kabir Nagar",
        locationName: "Sant Kabir Nagar (District)",
      },
      {
        locationValue: "Siddharthnagar",
        locationName: "Siddharthnagar (District)",
      },
      {
        locationValue: "Bahraich",
        locationName: "Bahraich (District)",
      },
      {
        locationValue: "Balarampur",
        locationName: "Balarampur (District)",
      },
      {
        locationValue: "Gonda",
        locationName: "Gonda (District)",
      },
      {
        locationValue: "Shravasti",
        locationName: "Shravasti (District)",
      },
      {
        locationValue: "Ayodhya",
        locationName: "Ayodhya (District)",
      },
      {
        locationValue: "Ambedkar Nagar",
        locationName: "Ambedkar Nagar (District)",
      },
      {
        locationValue: "Barabanki",
        locationName: "Barabanki (District)",
      },
      {
        locationValue: "Sultanpur",
        locationName: "Sultanpur (District)",
      },
      {
        locationValue: "Amethi",
        locationName: "Amethi (District)",
      },
      {
        locationValue: "Banda",
        locationName: "Banda (District)",
      },
      {
        locationValue: "Chitrakoot",
        locationName: "Chitrakoot (District)",
      },
      {
        locationValue: "Hamirpur",
        locationName: "Hamirpur (District)",
      },
      {
        locationValue: "Mahoba",
        locationName: "Mahoba (District)",
      },
      {
        locationValue: "Deoria",
        locationName: "Deoria (District)",
      },
      {
        locationValue: "Gorakhpur",
        locationName: "Gorakhpur (District)",
      },
      {
        locationValue: "Kushinagar",
        locationName: "Kushinagar (District)",
      },
      {
        locationValue: "Maharajganj",
        locationName: "Maharajganj (District)",
      },
      {
        locationValue: "Auraiya",
        locationName: "Auraiya (District)",
      },
      {
        locationValue: "Etawah",
        locationName: "Etawah (District)",
      },
      {
        locationValue: "Farrukhabad",
        locationName: "Farrukhabad (District)",
      },
      {
        locationValue: "Kannauj",
        locationName: "Kannauj (District)",
      },
      {
        locationValue: "Kanpur Dehat",
        locationName: "Kanpur Dehat (District)",
      },
      {
        locationValue: "Kanpur Nagar",
        locationName: "Kanpur Nagar (District)",
      },
      {
        locationValue: "Jalaun",
        locationName: "Jalaun (District)",
      },
      {
        locationValue: "Jhansi",
        locationName: "Jhansi (District)",
      },
      {
        locationValue: "Lalitpur",
        locationName: "Lalitpur (District)",
      },
      {
        locationValue: "Hardoi",
        locationName: "Hardoi (District)",
      },
      {
        locationValue: "Lakhimpur Kheri",
        locationName: "Lakhimpur Kheri (District)",
      },
      {
        locationValue: "Lucknow",
        locationName: "Lucknow (District)",
      },
      {
        locationValue: "Raebareli",
        locationName: "Raebareli (District)",
      },
      {
        locationValue: "Sitapur",
        locationName: "Sitapur (District)",
      },
      {
        locationValue: "Unnao",
        locationName: "Unnao (District)",
      },
      {
        locationValue: "Mirzapur",
        locationName: "Mirzapur (District)",
      },
      {
        locationValue: "Sant Ravidas Nagar",
        locationName: "Sant Ravidas Nagar (District)",
      },
      {
        locationValue: "Sonbhadra",
        locationName: "Sonbhadra (District)",
      },
      {
        locationValue: "Baghpat",
        locationName: "Baghpat (District)",
      },
      {
        locationValue: "Bulandshahar",
        locationName: "Bulandshahar (District)",
      },
      {
        locationValue: "Gautam Buddh Nagar",
        locationName: "Gautam Buddh Nagar (District)",
      },
      {
        locationValue: "Ghaziabad",
        locationName: "Ghaziabad (District)",
      },
      {
        locationValue: "Meerut",
        locationName: "Meerut (District)",
      },
      {
        locationValue: "Hapur",
        locationName: "Hapur (District)",
      },
      {
        locationValue: "Bijnor",
        locationName: "Bijnor (District)",
      },
      {
        locationValue: "Amroha",
        locationName: "Amroha (District)",
      },
      {
        locationValue: "Moradabad",
        locationName: "Moradabad (District)",
      },
      {
        locationValue: "Rampur",
        locationName: "Rampur (District)",
      },
      {
        locationValue: "Sambhal",
        locationName: "Sambhal (District)",
      },
      {
        locationValue: "Chandauli",
        locationName: "Chandauli (District)",
      },
      {
        locationValue: "Ghazipur",
        locationName: "Ghazipur (District)",
      },
      {
        locationValue: "Jaunpur",
        locationName: "Jaunpur (District)",
      },
      {
        locationValue: "Varanasi",
        locationName: "Varanasi (District)",
      },
      {
        locationValue: "Muzaffarnagar",
        locationName: "Muzaffarnagar (District)",
      },
      {
        locationValue: "Saharanpur",
        locationName: "Saharanpur (District)",
      },
      {
        locationValue: "Shamli",
        locationName: "Shamli (District)",
      },
    ],
    Bihar: [
      {
        locationValue: "Danapur",
        locationName: "Danapur Sadan",
      },
      {
        locationValue: "Jehanabad",
        locationName: "Jehanabad (District)",
      },
      {
        locationValue: "Arwal",
        locationName: "Arwal (District)",
      },
      {
        locationValue: "Paliganj",
        locationName: "Paliganj",
      },

      {
        locationValue: "Gaya",
        locationName: "Gaya (District)",
      },
      {
        locationValue: "Aurangabad",
        locationName: "Aurangabad (District)",
      },
      {
        locationValue: "Rohtas",
        locationName: "Rohtas (District)",
      },
      {
        locationValue: "Kaimur",
        locationName: "Kaimur (District)",
      },
      {
        locationValue: "Buxar",
        locationName: "Buxar (District)",
      },
      {
        locationValue: "Arrah",
        locationName: "Arrah(Bhojpur) (District)",
      },

      {
        locationValue: "Biharsharif",
        locationName: "Biharsharif/Nalanda (District)",
      },
      {
        locationValue: "Sheikhpura",
        locationName: "Sheikhpura (District)",
      },

      {
        locationValue: "Lakhisarai",
        locationName: "Lakhisarai (District)",
      },
      {
        locationValue: "Munger",
        locationName: "Munger (District)",
      },
      {
        locationValue: "Begusarai",
        locationName: "Begusarai (District)",
      },

      {
        locationValue: "Bhagalpur",
        locationName: "Bhagalpur (District)",
      },

      {
        locationValue: "Katihar",
        locationName: "Katihar (District)",
      },
      {
        locationValue: "Banka",
        locationName: "Banka (District)",
      },

      {
        locationValue: "Muzaffarpur",
        locationName: "Muzaffarpur (District)",
      },
      {
        locationValue: "Vaishali",
        locationName: "Vaishali (District)",
      },
      {
        locationValue: "Samastipur",
        locationName: "Samastipur (District)",
      },
      {
        locationValue: "Darbhanga",
        locationName: "Darbhanga (District)",
      },

      {
        locationValue: "West Champaran",
        locationName: "West Champaran (District)",
      },
      {
        locationValue: "Sheohar",
        locationName: "Sheohar (District)",
      },
      {
        locationValue: "Sitamarhi",
        locationName: "Sitamarhi (District)",
      },
      {
        locationValue: "East Champaran",
        locationName: "East Champaran (District)",
      },

      {
        locationValue: "Saharsa",
        locationName: "Saharsa (District)",
      },
      {
        locationValue: "Madhubani",
        locationName: "Madhubani (District)",
      },
      {
        locationValue: "Khagaria",
        locationName: "Khagaria (District)",
      },
      {
        locationValue: "Supaul",
        locationName: "Supaul (District)",
      },
      {
        locationValue: "Kishanganj",
        locationName: "Kishanganj (District)",
      },
      {
        locationValue: "Araria",
        locationName: "Araria (District)",
      },
      {
        locationValue: "Madhepura",
        locationName: "Madhepura (District)",
      },

      {
        locationValue: "Gopalganj",
        locationName: "Gopalganj (District)",
      },
      {
        locationValue: "Siwan",
        locationName: "Siwan (District)",
      },
      {
        locationValue: "Chapra",
        locationName: "Chapra (District)",
      },
    ],
  },
  distributorAreaCoverage: {
    Danapur: [
      "Ganghara",
      "Hathia Kandh",
      "Hetanpur",
      "Jamaluddin",
      "Jamsaut",
      "Patlapur",
      "Sarari",
      "Kasim Chak",
      "Kothawan",
      "Lakhani",
      "Bigha",
      "Manas",
      "Mobarakpur-Raghurampur",
      "Purani Panapur",
    ],
    Jehanabad: [
      "Jehanabad",
      "Makhdumpur",
      "Ghosi",
      "Hulasganj",
      "Ratni",
      "Faridpur",
      "Modanganj",
      "Kako",
    ],
    Arwal: ["Kaler", "Karpi", "Kurtha", "Arwal", "Sonbhadra Banshi Suryapur"],
    Paliganj: ["Paliganj", "Dulhin Bazar", "Bikram"],
    Gaya: [
      "Gaya Sadar",
      "Manpur",
      "Belaganj",
      "Bodhgaya",
      "Tankuppa",
      "Fatehpur",
      "Wazirganj",
      "Tekari",
      "Konch",
      "Guraru",
      "Paraiya",
      "Sherghati",
      "Gurua",
      "Amas",
      "Bankey ",
      "Bazar",
      "Imamganj",
      "Dumariya",
      "Barachatti",
      "Mohanpur",
      "Dobhi",
    ],
    Aurangabad: [
      "Aurangabad",
      "Barun",
      "Daudnagar",
      "Deo",
      "Goh",
      "Haspura",
      "Kutumba",
      "Madanpur",
      "Nabinagar",
      "Obra",
      "Rafiganj",
    ],
    Rohtas: [
      "Akorhi ",
      "Gola",
      "Bikramganj",
      "Chenari",
      "Dawath",
      "Dehri",
      "Dinara",
      "Karakat",
      "Kargahar",
      "Kochas",
      "Nasriganj",
      "Nauhatta",
      "Nokha",
      "Rajpur",
      "Rohtas",
      "Sanjhauli",
      "Sasaram",
      "Sheosagar",
      "Suryapura",
      "Tilouthu",
    ],
    Kaimur: [
      "Adhaura",
      "Bhabua",
      "Bhagwanpur",
      "Chainpur",
      "Chand",
      "Durgawati",
      "Kundra",
      "Mohania",
      "Nuaon",
      "Ramgarh",
      "Rampur",
    ],
    Buxar: [
      "Barhmpur",
      "Buxer",
      "Chakki",
      "Chaugain",
      "Chausa",
      "Dumraon",
      "Itarhi",
      "Kesath",
      "Nawanagar",
      "Rajpur",
      "Simri",
    ],
    Arrah: [
      "Arrah",
      "Agiaon",
      "Barhara",
      "Bihiya",
      "Charpokhari",
      "Garhani",
      "Jagdispur",
      "Koilwar",
      "Piro",
      "Udwantnagar",
      "Sahar",
      "Sandesh",
      "Shahpur",
      "Tarari",
    ],
    Biharsharif: [
      "Asthawan",
      "Ben",
      "Bihar",
      "Bind",
      "Chandi",
      "Ekangarsarai",
      "Giriak",
      "Harnaut",
      "Islampur",
      "Karai Parsurai",
      "Katrisarai",
      "Nagar Nausa",
      "Noorsarai",
      "Parbalpur",
      "Rahui",
      "Sarmera",
      "Silao",
      "Tharthari",
    ],
    Sheikhpura: [
      "Ariari",
      "Barbigha",
      "Chewara",
      "Ghat ",
      "Kusumbha",
      "Sheikhpura",
      "Shekhopur Sarai",
    ],
    Lakhisarai: ["Sadar Lakhisarai", "Surajgarha", "Halsi"],
    Munger: [
      "Asarganj",
      "Bariarpur",
      "Dharhara",
      "Jamalpur",
      "Kharagpur",
      "Munger",
      "Sangrampur",
      "Tarapur",
      "Tetiha Bambor",
    ],
    Begusarai: [
      "Bachhwara",
      "Bakhri",
      "Balia",
      "Begusarai",
      "Bhagwanpur",
      "Birpur",
      "Cheria Bariarpur",
      "Chhorahi",
      "Dandari",
      "Garhpura",
      "Khudabandpur",
      "Mansurchak",
      "Matihani",
      "Naokothi",
      "Sahebpur kamal",
      "Shamho Akha kurha",
      "Teghra",
    ],
    Bhagalpur: [
      "Nathnagar",
      "Sabour",
      "Shahkund",
      "Sultanganj",
      "Kahalgaon",
      "Sanhaula",
      "Jagdishpur",
      "Bihpur",
      "Colgong",
      "Gopalpur",
      "Goradih",
      "Ismailpur",
      "Kharik",
      "Narayanpur",
      "Naugachhia",
      "Pirpainti",
      "Rangra Chowk",
      "Sonhaula",
    ],
    Katihar: [
      "Katihar",
      "Dandkhora",
      "Hasanganj",
      "Korha",
      "Sameli",
      "Falka",
      "Kursela",
      "Barari",
      "Mansahi",
      "Pranpur",
      "Barsoi",
      "Balrampur",
      "Azamnagar",
      "Kadwa",
      "Manihari",
      "Amdabad",
    ],
    Banka: [
      "Amarpur",
      "Banka",
      "Barahat",
      "Belhar",
      "Bounsi",
      "Chandan",
      "Dhoraiya",
      "Fullidumar",
      "Katoriya",
      "Rajoun",
      "Sambhuganj",
    ],
    Muzaffarpur: [
      "Aurai",
      "Bandra",
      "Bochahan",
      "Gaighat",
      "Kanti",
      "Katra",
      "Kurhani",
      "Marwan",
      "Minapur",
      "Motipur",
      "Muraul",
      "Mushahari",
      "Sahebganj",
      "Sakra",
      "Paroo",
      "Saraiya",
    ],
    Vaishali: [
      "Bhagwanpur",
      "Bidupur",
      "Chehra kalan",
      "Desri",
      "Goraul",
      "Hajipur",
      "Jandaha",
      "Lalganj",
      "Mahnar",
      "Mahua",
      "Patepur",
      "Paterhi Belsar",
      "Raghopur",
      "Raja Pakar",
      "Sahdai Buzurg",
      "Vaishali",
    ],
    Samastipur: [
      "Bibhutpur",
      "Bithan",
      "Dalsinghsarai",
      "Hasanpur",
      "Kalyanpur",
      "Khanpur",
      "Mohanpur          ",
      "Mohiuddinagar",
      "Morwa",
      "Patori",
      "Pusa",
      "Rosera",
      "Samastipur",
      "Sarairanjan",
      "Sivaji nagar",
      "Singhia",
      "Tajpur",
      "Ujiarpur",
      "Vidyapati Nagar",
      "Warisnagar",
    ],
    Darbhanga: [
      "Darbhanga Sadar",
      "Bahadurpur",
      "Baheri",
      "Hayaghat",
      "Hanuman Nagar",
      "Keoti",
      "Jale",
      "Singhwara",
      "Manigachhi",
      "Tardih",
    ],
    "West Champaran": [
      "Bagaha",
      "Bairia",
      "Bettiah",
      "Bhitaha",
      "Chanpatia",
      "Gaunaha",
      "Jogapatti",
      "Lauriya",
      "Madhubani",
      "Mainatanr",
      "Majhaulia",
      "Narkatiaganj",
      "Nautan",
      "Piprasi",
      "Ramnagar",
      "Sidhaw",
      "Sikta",
      "Thakrahan",
    ],
    Sheohar: [
      "Dumri Katsarai",
      "Piprarhi",
      "Purnahiya",
      "Sheohar",
      "Tariani Chowk",
    ],
    Sitamarhi: [
      "Bairgania",
      "Bajpatti",
      "Bathnaha",
      "Belsand",
      "Bokhara",
      "Charaut",
      "Dumra",
      "Majorganj",
      "Nanpur",
      "Parihar",
      "Parsauni",
      "Pupri",
      "Riga",
      "Runisaidpur",
      "Sonbhadra",
      "Suppi",
      "Sursand",
    ],
    "East Champaran": [
      "Adapur",
      "Areraj",
      "Banjaria",
      "Chakia",
      "Chiraia",
      "Dhaka",
      "Ghorasahan",
      "Harsidhi",
      "Kalyanpur",
      "Kesaria",
      "Kotwa",
      "Madhuban",
      "Mehsi",
      "Motihari",
      "Narkatia",
      "Paharpur",
      "Pakri ",
      "Dayal",
      "Patahi",
      "Phenhara",
      "Piprakothi",
      "Ramgarhwa",
      "Raxaul",
      "Sangrampur",
      "Sugauli",
      "Tetaria",
      "Turkaulia",
    ],
    Saharsa: [
      "Kahra",
      "Sattar ",
      "Kataiya",
      "Nauhatta",
      "Mahishi",
      "Sour ",
      "Bazar",
      "Sonbarsa",
      "Patarghat",
      "Simri Bakhtiyarpur",
      "Salkhua",
      "Banma Ithari",
    ],
    Madhubani: [
      "Andhratharhi",
      "Babubarhi",
      "Basopatti",
      "Benipatti",
      "Bisfi",
      "Ghoghardiha",
      "Harlakhi",
      "Jainagar",
      "Jhanjharpur",
      "Kaluahi",
      "Khajauli",
      "Ladania",
      "Lakhnaur",
      "Laukaha",
      "Madhepur",
      "Madhubani",
      "Madhwapur",
      "Pandaul",
      "Phulparas",
      "Rajnagar",
    ],
    Khagaria: [
      "Alauli",
      "Beldaur",
      "Chautham",
      "Gogri",
      "Khagaria",
      "Mansi",
      "Parbatta",
    ],
    Supaul: [
      "Basantpur",
      "Chhatapur",
      "Kishanpur",
      "Marauna",
      "Nirmali",
      "Pipra",
      "Pratapganj",
      "Raghopur",
      "Saraigarh Bhaptiyahi",
      "Supaul",
      "Tribeniganj",
    ],
    Kishanganj: [
      "Bahadurganj",
      "Dighalbank",
      "Kishanganj",
      "Kochadhaman",
      "Pothia",
      "Terhagachh",
      "Thakurganj",
    ],
    Araria: [
      "Araria",
      "Jokihat",
      "Kursakanta",
      "Raniganj",
      "Sikti",
      "Palasi",
      "Forbesganj",
      "Narpatganj",
      "Bhargama",
    ],
    Madhepura: [
      "Alamnagar",
      "Bihariganj",
      "Chausa",
      "Gamharia",
      "Ghailarh",
      "Gwalpara",
      "Kishanganj",
      "Kumarkhand",
      "Madhepura",
      "Murliganj",
      "Puraini",
      "Shankarpur",
      "Singheshwar",
    ],
    Gopalganj: [
      "Baikunthpur",
      "Barauli",
      "Bhorey",
      "Bijaipur",
      "Gopalganj",
      "Hathua",
      "Katiya",
      "Kuchaikote",
      "Manjha",
      "Pach Deuri",
      "Phulwaria",
      "Sidhwalia",
      "Thawe",
      "Uchkagaon",
    ],
    Siwan: [
      "Andar",
      "Barharia",
      "Basantpur",
      "Bhagwanpur Hat",
      "Darauli",
      "Daraundha",
      "Goriakothi",
      "Guthani",
      "Hasanpura",
      "Hussainganj",
      "Lakri Nabiganj",
      "Maharajganj",
      "Nautan",
      "Mairwa",
      "Pachrukhi",
      "Raghunathpur",
      "Siswan",
      "Siwan",
      "Ziradei",
    ],
    Chapra: [
      "Amnour",
      "Baniapur",
      "Chapra",
      "Dariapur",
      "Dighwara",
      "Ekma",
      "Garkha",
      "Ishupur",
      "Jalalpur",
      "Lahladpur",
      "Maker",
      "Manjhi",
      "Marhaura",
      "Mashrakh",
      "Nagra",
      "Panapur",
      "Parsa",
      "Revelganj",
      "Sonepur",
      "Taraiya",
    ],
    Aligarh: [
      "Khair",
      "Gobhana",
      "Chandaus",
      "Jawan",
      "Lodha",
      "Dhanipur",
      "Akrabad",
      "Iglas",
      "Gonda",
      "Atrauli",
      "Bijauli",
      "Gangeri",
    ],
    Etah: [
      "Sheetalpur	Etah",
      "Sakit",
      "Nidhauli Kalan",
      "Marahara",
      "Jalesar",
      "Awagarh ",
      "Jaithara",
      "Aliganj",
    ],
    Hathras: [
      "Hathras",
      "Murasn",
      "Sasni",
      "Sikndra Rao",
      "Hasayan",
      "Sadabad",
      "Sahpau",
    ],
    Kasganj: [
      "Kasganj",
      "Soron",
      "Patiyali",
      "Ganjdundwara",
      "Sidhpura",
      "Sahawar",
      "Amanpur",
    ],
    Agra: [
      "Achnera",
      "Fatehpur Sikri",
      "Akola",
      "Bichpuri",
      "Baroli Ahir",
      "Khandoli",
      "Etmadpur",
      "Jagner",
      "Kheragarh",
      "Sainyan",
      "Shamsabad",
      "Fatehabad",
      "Pinahat",
      "Bah",
      "Jaitpur Kalan",
    ],
    Mathura: [
      "NandGaon",
      "ChhataChaumuha",
      "Goverdhan",
      "Mathura",
      "Farah",
      "Raya",
      "Baldeo",
      "Naujheel",
      "Mant",
    ],
    Mainpuri: [
      "Barnahal",
      "Mainpuri",
      "Bewar",
      "Ghiror",
      "Jageer",
      "Karhal",
      "Kishni",
      "Kuraoli",
      "Sultanganj",
    ],
    Firozabad: [
      "Firozabad",
      "Shikohabad",
      "Tundla",
      "Jasrana",
      "Eka",
      "Narkhi",
      "Madanpur",
      "AraonHathwant",
    ],
    Azamgarh: [
      "Ahiraula",
      "Atrauliya",
      "Azamatgarh",
      "Bilariyaganj",
      "Hariya",
      "Jahanaganj",
      "Koilsa",
      "Lalganj",
      "Maharajganj",
      "Martinganj",
      "Mehnagar",
      "Mirzapur",
      "Mohammadpur",
      "Tehbarpur",
      "Palhna",
      "Palhani",
      "Pawai",
      "Phoolpur",
      "Rani Ki Sarai",
      "Sathiyaon Tarwa",
      "Thekma",
    ],
    Ballia: [
      "Bansdih",
      "Belhari",
      "Beruarwari",
      "Chilkahar",
      "Dubhad",
      "Garwar",
      "Hanumanganj",
      "Maniyar",
      "Murli Chhapra",
      "Nagra",
      "Navanagar",
      "Pandah",
      "Rasra",
      "Revati",
      "Siar",
      "Sohaon",
      "Bairia",
    ],
    Mau: [
      "Badraon",
      "Dohri ",
      "Ghat",
      "Fatehpur Madaun",
      "Ghosi Kopaganj",
      "Mohammadabad Gohana",
      "Pardaha",
      "Ranipur",
      "Ratanpura",
    ],
    Prayagraj: [
      "Kaurihar",
      "Soraon",
      "Holagarh",
      "Mauaima",
      "Soraon",
      "Bahariya",
      "Phulpur",
      "Bahadurpur",
      "Pratappur",
      "Saidabad",
      "Dhanupur",
      "Handia",
      "Jasra",
      "Shankargarh  ",
      "Chaka",
      "Karchhana",
      "Kaundhiyara",
      "Uruwa",
      "Meja",
      "Koraon",
      "Manda   ",
      "Sahson",
      "Shringverpur Dham",
      "Bara",
    ],
    Fatehpur: [
      "Asothar",
      "Fatehpur",
      "Bahua",
      "Bhitaura",
      "Haswa",
      "Teliyani",
      "Amauli",
      "Deomai",
      "Khajuha",
      "Malwan",
      "Airaya Dhata",
      "Hathgam",
      "Vijayipur",
    ],
    Kaushambi: [
      "Chail",
      "Kara",
      "Kaushambi",
      "Manjhanpur",
      "Mooratganj",
      "Nevada",
      "Sarsawan ",
      "Sirathu",
    ],
    Pratapgarh: [
      "Babaganj",
      "Bihar",
      "Kalakankar",
      "Rampur Sangramgarh",
      "Sangipur",
      "Laxmanpur",
      "Mandhata ",
      "Sandwachandrika",
      "Aspurdeosara",
      "Baba Belkhar Nath Dham",
      "Mangrora",
      "Shivgarh",
      "Gaura",
      "Sadar  ",
      "Patti",
      "Kunda",
      "Lalganj",
    ],
    Bareilly: [
      "Aalampur Jafarabad",
      "Baheri",
      "Bhadpura",
      "Bhojipura",
      "Bhuta",
      "Bithiri Chainpur",
      "Damkhauda ",
      "Faridpur",
      "Fatehganj West",
      "Kyara",
      "Majhgawan",
      "Mirganj",
      "Nawabganj",
      "Ramnagar  ",
      "Shergarh",
    ],
    Pilibhit: [
      "Amariya",
      "Barkhera",
      "Bilsanda",
      "Bisalpur",
      "Lalaurikhera",
      "Marori",
      "Puranpur",
    ],
    Shahjahanpur: [
      "Banda",
      "Khutar",
      "Powayan",
      "Sindhauli",
      "Katra Khudaganj",
      "Jaitipur",
      "Tilhar",
      "Nigohi",
      "Kanth",
      "Dadraul",
      "Bhawalkhera",
      "Madnapur",
      "Kalan",
      "Mirzapur",
      "Jalalabad",
    ],
    Badaun: [
      "Ambiapur",
      "Asafpur",
      "Bisauli",
      "Dehgwan",
      "Dataganj",
      "Islamnagar",
      "Jagat ",
      "Mion",
      "Qadarchowk",
      "Sahaswan",
      "Salarpur",
      "Samrer",
      "Ujhani",
      "Usawan ",
      "Wazirganj",
    ],
    Basti: [
      "Basti",
      "Bahadurpur",
      "Bankati",
      "Gaur",
      "Harraiya",
      "Kaptanganj",
      "Kudaraha ",
      "Paras Rampur",
      "Ramnagar",
      "Rudhauli ",
      "Saltaua Gopalpur",
      "Sau Ghat",
      "Vikramjot",
      "Dubauliya",
    ],
    "Sant Kabir Nagar": [
      "Mehdawal",
      "Baghauli",
      "Pauli",
      "Semariyaw",
      "Santha",
      "Nathnagar",
      "Khalilabad",
      "Belhar",
      "Hainsar Bazar",
    ],
    Siddharthnagar: [
      "Naugarh",
      "Barhni",
      "Shohartgarh",
      "Birdpur",
      "Jogia",
      "Uska Bazar",
      "Bansi ",
      "Khesraha",
      "Bhanwapur",
      "Itwa",
      "Khuniyaon",
      "Dumariyaganj",
      "Lotan",
      "Methwal",
    ],
    Bahraich: [
      "Hujurpur",
      "Mahasi",
      "Pakharpur",
      "Chittaura",
      "Mihinpurwa",
      "Shivpur",
      "Risia ",
      "Visheshwarganj",
      "Jarwal",
      "Nawabganj",
      "Tejwapur",
      "Kaisarganj",
      "Balha",
      "Payagpur",
    ],
    Balarampur: [
      "Harriya Satgharwa",
      "Balrampur",
      "Tulsipur",
      "Gainsari",
      "Pachperwa",
      "Sridattganj",
      "Utraula  ",
      "Gaindas Bujurg",
      "Rehra Bazar",
    ],
    Gonda: [
      "Babhanjot",
      "Belsar",
      "Chhapia",
      "Colonelganj",
      "Haldharmau",
      "Itia Thok",
      "Jhanjhari  ",
      "Katra ",
      "Bazar",
      "Mankapur",
      "Mujehana",
      "Nawabganj",
      "Pandri ",
      "Kripal",
      "Paraspur",
      "Rupaidih    ",
      "Tarabganj",
      "Wazirganj",
    ],
    Shravasti: ["Hariharpur Rani", "Sirsiya", "Jamunaha", "Ikauna", "Gilaula"],
    Ayodhya: [
      "Masodha",
      "Sohawal",
      "Bikapur",
      "Milkipur",
      "MayaBazar",
      "PuraBazar",
      "Haringtonganj",
      "Amaniganj",
      "Tarun",
      "Mawai",
      "Rudauli",
    ],
    "Ambedkar Nagar": [
      "Akbarpur",
      "Baskhari",
      "Bhiti",
      "Bhiyaon",
      "Jahageerganj",
      "Jalalpur",
      "Katehari ",
      "Ramnagar",
      "Tanda",
    ],
    Barabanki: [
      "Banki",
      "Masauli",
      "Dewa",
      "Harakh",
      "Fatehpur",
      "Haidergarh",
      "Dariyabad",
      "Suratganj",
      "Siddhaur",
      "Pure Dalai",
      "Nindura",
      "Trivediganj",
      "Ramnagar",
      "Sirauli Ghauspur",
      "Banikodar",
    ],
    Sultanpur: [
      "Dubeypur",
      "Kurebhar",
      "Kurwar",
      "Bhadaiyan",
      "Lambhua",
      "Pratappur Kamaicha",
      "Jaisinghpur ",
      "Motigarpur",
      "Karaundi kalan",
      "Kadipur",
      "Dostpur",
      "Akhandnagar",
      "Dhanpatganj",
      "Baldirai",
    ],
    Amethi: [
      "Amethi",
      "Gauriganj",
      "Musafirkhana",
      "Tiloi",
      "Jagdishpur",
      "Bazar Shukul",
      "Bhetua",
      "Bhadar",
      "Sangrampur",
      "Shahgarh",
      "Jamo",
      "Singhpur",
      "Bhadurpur ",
    ],
    Banda: [
      "Badokhar Khurd",
      "Banda",
      "Mahuva",
      "Naraini",
      "Baberu",
      "Kamasin",
      "Jaspura ",
      "Tindwari",
    ],
    Chitrakoot: ["Karwi", "Mau", "Pahari", "Ramnagar", "Manikpur"],
    Hamirpur: [
      "Hamirpur",
      "Nadaun",
      "Bijhari",
      "Bhoranj",
      "Sujanpur",
      "Bamson",
    ],
    Mahoba: ["Kabrai", "Charkhari", "Jaitpur", "Panwari"],
    Deoria: [
      "Baitalpur",
      "Bankata",
      "Barhaj",
      "Bhaluani",
      "Bhagalpur",
      "Bhatni",
      "Bhatparrani ",
      "Deoria Sadar",
      "Desahi Deoria",
      "Gauri Bazar",
      "Lar",
      "Pathardeva",
      "Rampur Karkhana",
      "Rudrapur ",
      "Salempur",
      "Tarkulwa",
    ],
    Gorakhpur: [
      "Campierganj",
      "Jungle Kaudia(Partial)",
      "Sadar",
      "Sahjanwa",
      "Khajni",
      "Chauri Chaura",
      "Bansgaon",
      "Gola",
      "Chargawa",
      "Khorabar",
      "Bhathat",
      "Pipraich",
      "Sahjanwa ",
      "Pali",
      "Piprauli",
      "Khajni",
      "Belghat",
      "SardarNagar",
      "Brahmpur",
      "Bansgaon",
      "Kauriram",
      "Gagaha",
      "Gola",
      "Barhalganj",
      "Uruwa",
    ],
    Kushinagar: [
      "Tamkuhi",
      "Dudahi",
      "Seorahi",
      "Kasia",
      "Fazilnagar",
      "Hata",
      "Motichak",
      "Sukrauli",
      "Vishnupura",
      "Padrauna",
      "Khadda",
      "Nebua Naurangiya",
      "Captainganj",
      "Ramkola",
    ],
    Maharajganj: [
      "Brijmanganj",
      "Dhani",
      "Partawal",
      "Paniyara",
      "Lakshmipur",
      "Ghughali",
      "Mithaura",
      "Nautanwa",
      "Pharenda",
      "Nichlaul",
      "Sadar",
      "Siswa",
    ],
    Auraiya: [
      "Auraiya ",
      "Bhagaynagar ",
      "Sahar ",
      "Achalda ",
      "Etwakatra ",
      "Bidhuan ",
      "Ajitmal",
    ],
    Etawah: [
      "Barhpur",
      "Basrehar",
      "Jaswantnagar",
      "Mahewa",
      "Saifai",
      "Chakarnagar",
      "Takha ",
      "Bharthana",
    ],
    Farrukhabad: [
      "Kamalganj",
      "Mohammadabad",
      "Kaimganj",
      "Nawabganj",
      "Shamshabad",
      "Rajepur",
    ],
    Kannauj: [
      "Chibramau",
      "Gugrapur",
      "Haseran",
      "Jalalabad",
      "Kannauj",
      "Saurikh",
      "Talgram",
      "Umarda",
    ],
    "Kanpur Dehat": [
      "Akbarpur ",
      "Maitha",
      "Sarvankheda",
      "Jhinjhak",
      "Rasulabad",
      "Amraudha",
      "Malasa ",
      "Sandalpur",
      "Rajpur",
    ],
    "Kanpur Nagar": [
      "Kakwan",
      "Bilhaur",
      "Shivrajpur",
      "Chaubeypur",
      "Kalyanpur",
      "Vidhnu",
      "Sarsaul",
      "Bhitargaon",
      "Patara",
      "Ghatampur",
    ],
    Jalaun: [
      "Rampura",
      "Kuthaund",
      "Madhogarh",
      "Nadigaon",
      "Jalaun",
      "Mahewa",
      "Kadaura ",
      "Dakore",
      "Konch",
    ],
    Jhansi: [
      "Babina",
      "Badagaon",
      "Bamaur ",
      "Bangra",
      "Chirgaon",
      "Gursrai",
      "Mauranipur",
      "Moth",
    ],
    Lalitpur: ["Talbehat", "Jakhaura", "Bar", "Birdha", "Mehroni", "Madawra"],
    Hardoi: [
      "Ahirori",
      "Bawan",
      "Behadar",
      "Bharawan",
      "Bharkhani",
      "Bilgram",
      "Hariyawan",
      "Harpalpur",
      "Kachhauna",
      "Kothawan",
      "Madhoganj",
      "Mallawan",
      "Pihani",
      "Sandi",
      "Sandila",
      "Shahabad",
      "Sursa",
      "Tadiyawan",
      "Tondarpur",
    ],
    "Lakhimpur Kheri": [
      "Lakhimpur",
      "Behjam",
      "Mitauli",
      "Pasgawan",
      "Gola",
      "Bankeyganj",
      "Bijuwa",
      "Paliya",
      "Issanagar",
      "Dhaurahara",
      "Nakaha",
      "Phoolbehar",
      "Ramiyabehar",
      "Nighasan",
      "Mohammdi",
    ],
    Lucknow: [
      "Mall",
      "Malihabad",
      "Chinhat",
      "Bakhshi Ka Talab",
      "Kakori",
      "Gosain ganj",
      "Sarojni nagar",
      "Mohanlal Ganj",
    ],
    Raebareli: [
      "Amawan",
      "Bachhrawan",
      "Sataon",
      "Dalmau",
      "Harchandpur",
      "Kheeron",
      "Lalganj",
      "Maharajganj",
      "Jagatpur",
      "Rahi",
      "Rohaniya",
      "Sareni",
      "Shivgarh",
      "Deen Shah Gaura",
      "Unchahar",
      "Deeh",
      "Chatoh",
      "Salon",
    ],
    Sitapur: [
      "Ailiya",
      "Behta",
      "Biswan",
      "Gondlamau",
      "Hargaon",
      "Kasmanda",
      "Khairabad",
      "Laharpur",
      "Machhrehta",
      "Mahmudabad",
      "Maholi",
      "Misrikh",
      "Pahala",
      "Parsendi",
      "Pisawan",
      "Rampur ",
      "Mathura",
      "Reusa",
      "Sakran",
      "Sidhauli",
    ],
    Unnao: [
      "Asoha",
      "Auras",
      "Bangarmau",
      "Bichhiya",
      "Bighapur",
      "Fatehpur Chaurasi",
      "Ganj Moradabad",
      "Hasanganj",
      "Hilauli",
      "Mianganj",
      "Nawabganj",
      "Purwa",
      "Safipur",
      "Sikandarpur Karan",
      "Sikandarpur Sarausi",
      "Sumerpur",
    ],
    Mirzapur: [
      "Chhanbey",
      "City",
      "Hallia",
      "Jamalpur",
      "Kon",
      "Lalganj",
      "Majhawan",
      "Narayanpur",
      "Pahari",
      "Patehara",
    ],
    "Sant Ravidas Nagar": [
      "Abholi",
      "Deegh",
      "Suriyawan",
      "Gyanpur",
      "Aurai",
      "Bhadohi",
    ],
    Sonbhadra: [
      "Robertsganj",
      "Ghorawal",
      "Chatra",
      "Nagwa",
      "Chopan",
      "Babhani",
      "Myorpur",
      "Duddhi",
      "Karma",
      "Kone",
    ],
    Baghpat: ["Baghpat", "Khekra", "Baraut", "Chhaprauli", "Binauli", "Pilana"],
    Bulandshahar: [
      "Bulandshahr",
      "Agauta",
      "Gulaothi",
      "Lakhaoti",
      "Sikandrabad",
      "Khurja",
      "Arnia",
      "Anoopshahr",
      "Jhangirabad",
      "Shikarpur",
      "Pahasu",
      "Siyana",
      "Unchagaon",
      "B B Nagar",
      "DibaiDanpur",
    ],
    "Gautam Buddh Nagar": ["Bisrakh", "Dadri", "Dankaur", "Jewar"],
    Ghaziabad: ["Rajapur", "Bhojpur", "Muradnagar", "Loni"],
    Meerut: [
      "Jaani",
      "Meerut",
      "Kharkhoda",
      "Rajpura",
      "Rohta",
      "Hastinapur",
      "Machara",
      "Mawana",
      "Parikshitgarh",
      "Daurala",
      "Sardhana",
      "Saroorpur",
    ],
    Hapur: ["Garhmukteshwar", "Dahaulana", "Simbhawali", "Hapur"],
    Bijnor: [
      "Mohammadpur Deomal",
      "Haldaur",
      "Kiratpur",
      "Najibabad",
      "Kotwali",
      "Nehtaur",
      "Noorpur",
      "Dhampur",
      "Afzalgarh",
      "Sehora",
      "Jalilpur",
    ],
    Amroha: [
      "Amroha",
      "Joya",
      "Hasanpur",
      "Dhanaura",
      "Gajraula",
      "Gangeshwari",
    ],
    Moradabad: [
      "Moradabad",
      "Mundapandey",
      "Bhagatpur Tanda",
      "Bilari",
      "Kundarki",
      "Kanth",
      "Chajlet",
      "Thakurdwara",
      "Dilari",
    ],
    Rampur: ["Bilaspur", "Chamrawa", "Milak", "Saidnagar", "Shahabad", "Swar"],
    Sambhal: [
      "Behjoi",
      "Sambhal",
      "Asmoli",
      "Rajpura",
      "Gunnaur",
      "Baniyakheda",
      "Junavi",
      "Panwasa",
    ],
    Chandauli: [
      "Barahani",
      "Chandauli",
      "Niyamatabad",
      "Chahaniya",
      "Sakaldiha",
      "Dhanapur",
      "Chakia",
      "Shahabganj",
      "Naugarh",
    ],
    Ghazipur: [
      "Ghazipur",
      "Virno",
      "Karanda",
      "Mardah",
      "Zamania",
      "Bhadaura",
      "Reotipur ",
      "Saidpur",
      "Deokali",
      "Sadat",
      "Jakhania",
      "Manihari",
      "Mohammadabad",
      "Bhanwarkol ",
      "Kasimabad",
      "Barachawar",
    ],
    Jaunpur: [
      "Badlapur",
      "Baksha",
      "Barasathi",
      "Dharmapur",
      "Dobhi",
      "Jalalpur",
      "Karanjakala",
      "Kerakat",
      "Khuthan",
      "Machhli Shahar",
      "Maharajganj",
      "Mariyahu",
      "Muftiganj",
      "Mungara Badshahpur",
      "Ramnagar",
      "Rampur",
      "Shahganj",
      "Sikarara",
      "Sirkoni",
      "Suithakala",
      "Sujanganj",
    ],
    Varanasi: [
      "Arajiline",
      "Baragaon",
      "Chirai Gaon",
      "Cholapur",
      "Harhua",
      "Kashi Vidya Peeth",
      "Pindara",
      "Sewapuri",
    ],
    Muzaffarnagar: [
      "Sadar – Kukda",
      "Budhana",
      "Baghra",
      "Shahpur",
      "Purquazi",
      "Charthawal",
      "Morna",
      "Jansath",
      "Khatauli",
    ],
    Saharanpur: [
      "Behat",
      "Sadholi Kadeem",
      "Saharanpur",
      "Muzaffarabad",
      "Punwarka",
      "Balia ",
      "Kheri",
      "Sarsawan",
      "Nakur",
      "Gangoh",
      "Rampur ",
      "Maniharan",
      "Nagal",
      "Nanauta",
      "Deoband",
    ],
    Shamli: ["Shamli", "Thanabhawan", "Kandhala", "Kairana", "Uun"],
  },
  stockistAreaCoverage: {
    Patna: [
      "Danapur Sadan",
      "Jehanabad (District)",
      "Arwal (District)",
      "Paliganj",
    ],
    Gaya: [
      "Gaya (District)",
      "Aurangabad (District)",
      "Rohtas (District)",
      "Kaimur (District)",
      "Buxar (District)",
      "Arrah(Bhojpur) (District)",
    ],
    Nawada: ["Biharsharif/Nalanda (District)", "Sheikhpura (District)"],
    Jamui: [
      "Lakhisarai (District)",
      "Munger (District)",
      "Begusarai (District)",
    ],
    Purnia: ["Katihar  (District)", "Banka  (District)"],
    Vaishali: [
      "Muzzafarpur (District)",
      "Vaishali (District)",
      "Samastipur (District)",
      "Darbhanga (District)",
    ],
    "East Champaran": [
      "West Champaran (District)",
      "Sheohar (District)",
      "Sitamarhi (District)",
      "East Champaran (District)",
    ],
    Madhepura: [
      "Saharsa (District)",

      "Madhubani (District)",

      "Khagaria (District)",
      "Supaul (District)",
      "Kishanganj (District)",
      "Araria (District)",

      "Madhepura  (District)",
    ],
    Siwan: ["Gopalganj (District)", "Siwan (District)", "Chapra (District)"],
    Bhagalpur: [" Bhagalpur (District)"],
    Aligarh: ["Aligarh", "Etah", "Hathras", "Kasganj"],
    Agra: ["Agra", "Mathura", "Mainpuri", "Firozabad"],
    Azamgarh: ["Azamgarh", "Ballia", "Mau"],
    Prayagraj: ["Prayagraj", "Fatehpur", "Kaushambi", "Pratapgarh"],
    Bareilly: ["Bareilly", "Pilibhit", "Shahjahanpur", "Badaun"],
    Basti: ["Basti", "Sant Kabir Nagar", "Siddharthnagar"],
    Gonda: ["Bahraich", "Balarampur", "Gonda", "Shravasti"],
    Ayodhya: ["Ayodhya", "Ambedkar Nagar", "Barabanki", "Sultanpur", "Amethi"],
    Banda: ["Banda", "Chitrakoot", "Hamirpur", "Mahoba"],
    Gorakhpur: ["Deoria", "Gorakhpur", "Kushinagar", "Maharajganj"],
    Kanpur: [
      "Auraiya",
      "Etawah",
      "Farrukhabad",
      "Kannauj",
      "Kanpur Dehat",
      "Kanpur Nagar",
    ],
    Jhansi: ["Jalaun", "Jhansi", "Lalitpur"],
    Lucknow: [
      "Hardoi",
      "Lakhimpur Kheri",
      "Lucknow",
      "Raebareli",
      "Sitapur",
      "Unnao",
    ],
    Mirzapur: ["Mirzapur", "Sant Ravidas Nagar", "Sonbhadra"],
    Meerut: [
      "Baghpat",
      "Bulandshahar",
      "Gautam Buddh Nagar",
      "Ghaziabad",
      "Meerut",
      "Hapur",
    ],
    Moradabad: ["Bijnor", "Amroha", "Moradabad", "Rampur", "Sambhal"],
    Varanasi: ["Chandauli", "Ghazipur", "Jaunpur", "Varanasi"],
    Saharanpur: ["Muzaffarnagar", "Saharanpur", "Shamli"],
  },
}
